name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
