name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # прием обновлений
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
